name: Continuous releases
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
concurrency:
  group: ${{ github.workflow }}
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: npm
      - name: Install dependencies
        run: npm ci  
      - name: Release package on pkg.pr.new
        run: npx pkg-pr-new publish --compact --comment=off